version: '3.8'

services:
  mitm:
    build:
      context: ./entrainement/mitm
    image: my_image_mitm
    container_name: mitm_container
    tty: true

  phishing:
    build:
      context: ./entrainement/phishing
    image: my_image_phishing
    container_name: phishing_container
    tty: true

  brute_force:
    build:
      context: ./entrainement/brute_force
    image: my_image_brute_force
    container_name: brute_force_container
    tty: true

  malware:
    build:
      context: ./entrainement/malware
    image: my_image_malware
    container_name: malware_container
    tty: true

  sql_injection:
    build:
      context: ./entrainement/sql_injection
    image: my_image_sql_injection
    container_name: sql_injection_container
    tty: true
